name: "Proxmox QDevice External Vote Support"
description: "Proxmox QDevice for External Vote Support"
version: "0.1.0"
slug: "proxmox_qdevice_external_vote_support"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "5403": "5403"
  "22": "22"
ports_description:
  "5403": "corosync-qnetd port"
  "22": "SSH port used during 'pvecm qdevice setup <QDEVICE-IP>'"
options:
  Port: 5403
  Server_TLS: "on"
  Client_TLS: "on"
  Debug: true
  Enable_SSH_Server: false ##### Off by default for security purposes #####
  AddOn_root_Password:
  public_keys:
    - public_key: "" # by default assume that corosync-qnetd is able to push its certificate
schema:
  Port: int
  Server_TLS: str
  Client_TLS: str
  Debug: bool
  Enable_SSH_Server: bool
  AddOn_root_Password: str
  public_keys:
    - public_key: str