name: "Proxmox QDevice External Vote Support"
description: "Proxmox QDevice for External Vote Support"
version: "0.1.0"
slug: "proxmox_qdevice_external_vote_support"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "5403": "5403"
  "22": "22"
ports_description:
  "5403": "corosync-qnetd port"
  "22": "SSH port used during 'pvecm qdevice setup <QDEVICE-IP>'"
options:
  Corosync-Port: 5403
  Server_TLS: "on"
  Client_TLS: "on"
  Debug: true
  SSH-Port: 22
  Initial_Setup: false ##### Off by default for security purposes #####
  Env_root_Password:
schema:
  Corosync-Port: int
  Server_TLS: str
  Client_TLS: str
  Debug: bool
  SSH-Port: int
  Initial_Setup: bool
  Env_root_Password: str(8,)